repos:
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.9
        args: ['--check', '--diff', '--verbose']
        verbose: true

  - repo: https://github.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        args: ['--config=.flake8', '--verbose']
        verbose: true

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        args:
          [
            '--rcfile=.pylintrc',
            '--output-format=colorized',
            '--score=y',
            '--fail-under=5.0',
            '--verbose'
          ]
        language_version: python3.9
        verbose: true
