repos:
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: ['--config=.flake8']
-   repo: https://github.com/pycqa/pylint
    rev: v3.2.7
    hooks:
    - id: pylint
      args: [
        "--rcfile=.pylintrc",  # Points to your pylint config file
        "--output-format=colorized", 
        "--score=y"  # This will show the pylint score in the output
      ]
      language_version: python3.9