version: "3"
services:

  django:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-backend:${COMMIT_ID}
    env_file:
      - docker/prod/docker_production.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - "8000:8000"

  worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-worker:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    env_file:
      - docker/prod/docker_production.env

  nodejs:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-frontend:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/nodejs/Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /code/node_modules
      - /code/bower_components

  remote-worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-remote-worker:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    command: ["python", "-m", "scripts.workers.remote_submission_worker"]
    env_file:
      - docker/prod/docker_remote_worker.env
