version: "3"
services:
  memcached:
    image: memcached:1.6.15
    ports:
      - "11211:11211"

  django:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-backend:${COMMIT_ID}
    env_file:
      - docker/prod/docker_production.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    ports:
      - "8000:8000"
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-group: django_production
        awslogs-create-group: "true"

  celery:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-celery:${COMMIT_ID}
    env_file:
      - docker/prod/docker_production.env
    build:
      context: ./
      dockerfile: docker/prod/celery/Dockerfile
    depends_on:
      - django
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: '1.0'
        reservations:
          memory: 800M
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-group: celery_production
        awslogs-create-group: "true"

  worker_py3_7:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-worker-py3.7:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker_py3_7/Dockerfile
    env_file:
      - docker/prod/docker_production.env

  worker_py3_8:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-worker-py3.8:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker_py3_8/Dockerfile
    env_file:
      - docker/prod/docker_production.env

  worker_py3_9:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-worker-py3.9:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker_py3_9/Dockerfile
    env_file:
      - docker/prod/docker_production.env

  nodejs:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-frontend:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/nodejs/Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /code/node_modules
      - /code/bower_components
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_DEFAULT_REGION}
        awslogs-group: nodejs_production
        awslogs-create-group: "true"

  remote-worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-remote-worker:${COMMIT_ID}
    build:
      context: ./
      dockerfile: docker/prod/worker_py3_7/Dockerfile
    command: [ "python", "-m", "scripts.workers.remote_submission_worker" ]
    env_file:
      - docker/prod/docker_remote_worker.env

  code-upload-worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/evalai-production-code-upload-worker:${COMMIT_ID}
    env_file:
      - docker/prod/docker_code_upload_worker.env
    build:
      context: ./
      dockerfile: docker/prod/code-upload-worker/Dockerfile

