global:
  scrape_interval: 30s
  external_labels:
    monitor: 'evalai-monitor'

rule_files:
  - /etc/rules/rules.yml

scrape_configs:
  - job_name: 'prometheus' 
    metrics_path: '/prometheus/metrics'
    static_configs: 
      - targets: ['localhost:9090']
      
  - job_name: 'statsd'
    metrics_path: '/statsd/metrics'
    static_configs:
      - targets: ['monitoring-staging.eval.ai']

  - job_name: 'node_exporter'
    metrics_path: '/node_exporter'
    static_configs:
      - targets: ['staging.eval.ai']

  - job_name: 'evalai'
    metrics_path: '/'
    static_configs:
      - targets: ['staging.eval.ai']

alerting:
  alertmanagers:
  - path_prefix: '/alert_manager'
    scheme: 'https'
    static_configs:
    - targets: ['monitoring-staging.eval.ai']
