title: Challenge Title
short_description: Short description of the challenge (preferably 140 characters)
description: description.html
evaluation_details: evaluation_details.html
terms_and_conditions: terms_and_conditions.html
image : logo.png
submission_guidelines: submission_guidelines.html
evaluation_script: evaluation_script.zip
start_date: 2017-06-09 20:00:00
end_date: 2017-06-19 20:00:00

leaderboard:
  - id: 1
    schema: {"labels": ["yes/no", "number", "others", "overall"], "default_order_by": "overall"}
  - id: 2
    schema: {"labels": ["metric_a", "metric_b"], "default_order_by": "metric_a"}

challenge_phases:
  - id: 1
    name: Challenge Phase 1
    description: challenge_phase_description.html
    leaderboard_public: True
    is_public: True
    start_date: 2017-06-09 20:00:00
    end_date: 2017-06-19 20:00:00
    test_annotation_file: test_annotation.txt
    codename: phase1
    max_submissions_per_day: 100
    max_submissions: 1000
    max_submissions_per_month: 1000
  - id: 2
    name: Challenge Phase 2
    description: challenge_phase_description.html
    leaderboard_public: True
    is_public: True
    start_date: 2017-06-09 20:00:00
    end_date: 2017-06-19 20:00:00
    test_annotation_file: test_annotation.txt
    codename: phase2
    max_submissions_per_day: 100
    max_submissions: 1000
    max_submissions_per_month: 1000

dataset_splits:
  - id: 1
    name: Name of the dataset split
    codename: codename of dataset split
  - id: 2
    name: Name of the dataset split 2
    codename: codename of dataset split 2

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 1
    leaderboard_id: 2
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 2
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
